raw_dess_dir: data/skm-tea-dataset/dess-files
raw_pd_dir: data/iu-dataset/pd-files
npy_root: data/npy
manifest_root: data/manifests

plane: sagittal
image_size: 256
stack_depth: 1
center_only_label: true

normalize_percentiles: [1, 99]
val_ratio: 0.1
seed: 42

# full data on Big Red
max_dess_subjects: null
max_pd_subjects: null

# spacing-aware in-plane resampling target
target_spacing_x: 0.3125
target_spacing_y: 0.3125


# keep only middle sagittal band later
midband_low_frac: 0.20
midband_high_frac: 0.80


vis_root: data/vis
save_debug_vis: true
max_vis_subjects_per_domain: 3
vis_slice_fracs: [0.3, 0.5, 0.7]