raw_dess_dir: data/skm-tea-data/nifti
raw_pd_dir: data/iu-dataset/nifti
npy_root: data/npy
manifest_root: data/manifests

plane: sagittal
image_size: 256
stack_depth: 1
center_only_label: true

normalize_percentiles: [1, 99]
val_ratio: 0.1
seed: 42

max_dess_subjects: 5
max_pd_subjects: 5