raw_dess_dir: data/skm-tea-data/nifti
raw_pd_dir: data/iu-datasets/nifti
npy_root: data/npy

plane: sagittal
image_size: 256
stack_depth: 3          # 2.5D
center_only_label: true

max_dess_subjects: 5    # change to 100 on Big Red
max_pd_subjects: 5      # change to 100 on Big Red

val_ratio: 0.1
seed: 42

input_nc: 3
output_nc: 3

train_mode: reggan