name: CycleGan
bidirect: False
regist: True
noise_level: 0
port: 6019

# save_root: './output/Cyc/bigred_full_run1/'
# image_save: './output/Cyc/bigred_full_run1/img/'
save_root: './output/Cyc/bigred_balanced_run1/'
image_save: './output/Cyc/bigred_balanced_run1/img/'


Adv_lamda: 1
Cyc_lamda: 10
Corr_lamda: 20
Smooth_lamda: 10

epoch: 0
n_epochs: 30
batchSize: 1

# dataroot: '../data/bigred_full_run1/train/'
# val_dataroot: '../data/bigred_full_run1/val/'
dataroot: '../data/npy_balanced/train/'
val_dataroot: '../data/npy_balanced/val/'

lr: 0.0001
decay_epoch: 15
size: 256

input_nc: 1
output_nc: 1
cuda: True
n_cpu: 8